//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationWHB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ankbu
    {
        public int Id { get; set; }
        public string PassengerName { get; set; }
        public string PassengerEmail { get; set; }
        public Nullable<int> koltukid { get; set; }
        public Nullable<int> price { get; set; }
    }
}
