//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationWHB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AccountsDbEntities10 : DbContext
    {
        public AccountsDbEntities10()
            : base("name=AccountsDbEntities10")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<busDate> busDates { get; set; }
        public DbSet<busTime> busTimes { get; set; }
        public DbSet<eskbu> eskbus { get; set; }
        public DbSet<izmbu> izmbus { get; set; }
        public DbSet<lastCity> lastCities { get; set; }
        public DbSet<Manager> Managers { get; set; }
        public DbSet<OrdersTable> OrdersTables { get; set; }
        public DbSet<soldticket> soldtickets { get; set; }
        public DbSet<Table> Tables { get; set; }
        public DbSet<ankbu> ankbus { get; set; }
        public DbSet<startCity> startCities { get; set; }
    }
}
