//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationWHB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersTable
    {
        public int id { get; set; }
        public string binis { get; set; }
        public string inis { get; set; }
        public int koltukid { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string date { get; set; }
    }
    public class OrderModel
    {
        public List<OrdersTable> orders { get; set; }

    }
}
